data:
    dataset: 'Finger'  # 'coco' 'hpatches'
    export_folder: 'ronghe' # train, val
    preprocessing:
        resize: [128, 128]
        # resize: [480, 640] 
    gaussian_label:
        enable: false # false
        sigma: 1.
    augmentation:
        photometric:
            enable: true
    homography_adaptation:
        enable: true
        num: 1 # 100
        aggregation: 'sum'
        filter_counts: 0
        homographies:
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.1
                perspective_amplitude_x: 0.05
                perspective_amplitude_y: 0.05
                allow_artifacts: true
                patch_ratio: 1
                max_angle: 1.57

training:
    workers_test: 2

model:
    # name: 'SuperPointNet' # 'SuperPointNet_gauss2'
    name: 'UnSuperPointNet_small' # 'SuperPointNet_gauss2'
    params: {
    }    
    batch_size: 1
    eval_batch_size: 1
    detection_threshold: 0.5 # 0.015
    nms: 6
    top_k: 500
    subpixel:
        enable: false

# pretrained: 'logs/magicpoint_synth20/checkpoints/superPointNet_200000_checkpoint.pth.tar' # 'SuperPointNet'
pretrained: 'logs/0922_small_encoder/checkpoints/superPointNet_50000_checkpoint.pth.tar'
# pretrained: 'logs/pre/superPointNet_49800_checkpoint.pth.tar'


