data:
#    name: 'synthetic_shapes'
    dataset: 'Read_txt2data_93_img_mask'
    primitives: 'all'
    truncate: {draw_ellipses: 0.3, draw_stripes: 0.2, gaussian_noise: 0.1}
    cache_in_memory: true
    suffix: 'v1'
    add_augmentation_to_test_set: true  # set to true to evaluate with noise
    gaussian_label:
        enable: false
        params:
            GaussianBlur: {sigma: 0.2}
    preprocessing: ## didn't do this
        blur_size: 21
        resize: [160, 48]
    augmentation:
        photometric:
            enable: false ## for class to recognize
            enable_train: false
            enable_val: false
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 20}
                random_contrast: {strength_range: [0.85, 1.15]}
                additive_gaussian_noise: {stddev_range: [0, 15]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.8]
                    kernel_size_range: [50, 100]
                motion_blur: {max_kernel_size: 7} # origin 7
            #  params:
            #     random_brightness: {max_abs_change: 75}
            #     random_contrast: {strength_range: [0.3, 1.8]}
            #     additive_gaussian_noise: {stddev_range: [0, 15]}
            #     additive_speckle_noise: {prob_range: [0, 0.0035]}
            #     additive_shade:
            #         transparency_range: [-0.5, 0.8]
            #         kernel_size_range: [50, 100]
            #     motion_blur: {max_kernel_size: 7} # origin 7
        homographic:
            enable: false
            enable_train: false
            enable_val: false
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.05
                perspective_amplitude_x: 0.05
                perspective_amplitude_y: 0.05
                patch_ratio: 1
                max_angle: 15 # 3.14  0.087 
                allow_artifacts: true
                translation_overflow: 0.05
                flip: True
            valid_border_margin: 2
    warped_pair:
        enable: false # false when training only on detector
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            patch_ratio: 0.85
            max_angle: 1.57
            allow_artifacts: true # true
        valid_border_margin: 3

front_end_model: 'Train_model_heatmap_8_pts_2'  # 'Train_model_frontend'
# front_end_model: 'Train_model_heatmap_8_pts'  # 'Train_model_frontend'

model:
    # name: 'UnSuperPointNet_small_8_theta_04_04'
    name: 'UnSuperPointNet_small_8_theta_student_block_v2_0814'
    params: {
    }
    detector_loss:
        loss_type: 'softmax'

    batch_size:  32 # 64
    eval_batch_size: 16
    learning_rate: 0.001
    kernel_reg: 0.
    detection_threshold: 0.5 # 1/65
    nms: 2
    lambda_loss: 0 # disable descriptor loss
    dense_loss:
        enable: false
        params:
            descriptor_dist: 4 # 4, 7.5
            lambda_d: 800 # 800
    sparse_loss:
        enable: true
        params:
            num_matching_attempts: 1000
            num_masked_non_matches_per_match: 100
            lamda_d: 1
            dist: 'cos'
            method: '2d'
    other_settings: 'train 2d, gauss 0.5'

retrain: True # set true for new model
# retrain: False # set true for new model
reset_iter: True

train_iter: 500000 # 200000
tensorboard_interval: 100 # 200
save_interval: 50 # 2000
validation_interval: 100 # one validation of entire val set every N training steps
validation_size: 10
train_show_interval: 100 # one show of the current training from to Tensorboard every N training steps
seed: 0

# pretrained: '/home/fengjy/Work/Work/6193_self_supervised/unsuperpoint_pts_alpha1_4/logs/test/checkpoints/superPointNet_10000_checkpoint.pth.tar'
# pretrained: '/data/yey/work/6191/unsuperpoint/logs/0617_1.5_4/checkpoints/superPointNet_82400_checkpoint.pth.tar'

# pretrained: 'logs/pretrained/superPointNet_43600_checkpoint.pth.tar'
pretrained: '/home/fengjy/Work/Work/6193_self_supervised/unsuperpoint_pts_new_trans_model_06_12_resize_160*48_v1_6/logs/06_12/unsuperpoint_160_48_06_12/checkpoints/superPointNet_81300_checkpoint.pth.tar'
pretrained: '/home/fengjy/Work/Work/6193_train_9800/unsuperpoint_pts_resize_160*48_0821_v1_2/logs/08_22/unsuperpoint_160_48_08_22/checkpoints/superPointNet_435000_checkpoint.pth.tar'